### ISSUE TITLE
vue-router配置history模式，线上访问时刷新返回404

### ISSUE THREAD

**Issue by monster1935** [javaSwing/NeteaseCloudWebApp#1]
vue-router开启了history模式，线上部署时是否要考虑redirect404页面的指向，现在线上的访问环境只能是访问***.index.html。不知道楼主开启history模式是否是做了其他的考虑？

**Comment by javaSwing** [comment]
对的，这个应该是服务端的处理下，我用的是百度云的BAE暂时还没有办法处理（望知道的告知下），目前知道方案是：在服务器进行请求的重定向，或者用Ng,详情见：https://segmentfault.com/q/1010000006167205

**Comment by javaSwing** [comment]
已经修改
