### ISSUE TITLE
node env未正确设置

### ISSUE THREAD

**Issue by cjz9032** [javaSwing/NeteaseCloudWebApp#12]
跑dev的时候，会跳过设置dev语句。
导致环境错误一系列的报错，如eslint的规则等等。

**Comment by cjz9032** [comment]
可以的话，我发个request

**Comment by cjz9032** [comment]
@

**Comment by javaSwing** [comment]
@cjz9032 请说下你是什么情况下出现的错误？我自己从github上下载了，重新运行，并没有出现你说的那个错误！

**Comment by cjz9032** [comment]
@javaSwi 没ng 
/build/dev-server.js 
`if (!process.env.NODE_ENV) process.env.NODE_ENV = JSON.parse(config.dev.env.NODE_ENV)`
我直接npm run dev,会默认带上去production环境.所以这里不会设置成dev环境问题.
然后这里的condition,我不知道你加上去是为什么,我以为直接去掉这个condition就好了,这样会有什么问题吗?

**Comment by javaSwing** [comment]
@cjz9032 这是vue-cli自动生成的，我没有动过这里的代码，你是不修改过这里的代码？

**Comment by cjz9032** [comment]
如果改过我就不会这么问了...
是cli生成的啊,不理解他的应用场景,我去问问

**Comment by javaSwing** [comment]
@cjz9032 好的

**Comment by cjz9032** [comment]
问题找到了:汇报一下,windows和linux之间的差异..需要个cross抹平就好了
https://github.com/vuejs-templates/webpack/issues/535

**Comment by javaSwing** [comment]
@cjz9032 有太多的坑，呵呵！努力填坑中

**Comment by cjz9032** [comment]
@javaSwing  ...这也不是你的坑吧,严格来说是windows 设置环境变量的问题.
不要慌,最近准备给自己放个假回家写代码,有时间鼓捣这些了

**Comment by javaSwing** [comment]
@cjz9032 有些东西就是系统之间的差异！所以说一处前端深似海啊！革命尚未成功，同志仍需努力！

**Comment by cjz9032** [comment]
@javaSwing 终于鼓捣出来docker了,装机工的活只要干一次就好了. 这种啥各种诡异的环境问题就可以无视了

**Comment by javaSwing** [comment]
@cjz9032 666666666666
