### ISSUE TITLE
as for lazyload

### ISSUE THREAD

**Issue by cjz9032** [javaSwing/NeteaseCloudWebApp#13]
看到log中其中更新一次"remove lazyload."
我想问下为什么remove掉了,我加回来后挺好用的呀
除了image'src filter必须用e.'attr来协助有点奇怪

**Comment by javaSwing** [comment]
@cjz9032 是因为当时那个版本的lazyload和目前使用的vue版本有冲突，紧急去了！有时候我测试下看看还有没有这个问题，没有的话会再加上去的！

**Comment by cjz9032** [comment]
@javaSwing 这样哦,message里没写原因挺尴尬的.版本的话最新1.0.3 我这1.0.1已经没问题了
PS:还有我看好久没commit,以为废弃了..所以我这没有专门起branch去改,不是很好提PR了..

**Comment by javaSwing** [comment]
嗯，当时有人在issues里提了，我直接修改了下！没有写原因。PS:的确很久没更新了，哈哈！工作有点忙！

**Comment by javaSwing** [comment]
@cjz9032 嗯，当时有人在issues里提了，我直接修改了下！没有写原因。PS:的确很久没更新了，哈哈！工作有点忙！

**Comment by cjz9032** [comment]
@javaSwing  我也是啊..趁着周末写点,哎,准备起分支去了..
