### ISSUE TITLE
部署在linux上出问题

### ISSUE THREAD

**Issue by Rbingo** [javaSwing/NeteaseCloudWebApp#14]
![image](https://cloud.githubusercontent.com/assets/18257488/25083331/0f65995c-2389-11e7-9604-d5d601990ac5.png)

**Comment by javaSwing** [comment]
@Rbingo 你没有自己修改了对应的配置文件，我自己在liunx下试了下，可以正常运行。从你发的图片上看，你node环境可能有问题，推荐使用nvm安装node环境
