### ISSUE TITLE
img的lazy="loading"这个属性是干什么，额，不明白哎

### ISSUE THREAD

**Issue by Susanping** [javaSwing/NeteaseCloudWebApp#15]

**Comment by javaSwing** [comment]
@Susanping   ##是懒加载的一个插件，[https://github.com/javaSwing/NeteaseCloudWebApp/issues/8](https://github.com/javaSwing/NeteaseCloudWebApp/issues/8)

**Comment by Susanping** [comment]
哦哦，执行myaudio.onsuspend这个函数，并没有一暂停音乐就触发啊，就只能暂停一次，才会触发这个函数，再次点击暂停，就不能触发这个函数了。这是为什么？

**Comment by javaSwing** [comment]
@Susanping 这个函数我没有用过，网上查了下是在浏览器读取媒体数据中止时执行 JavaScript ，加载完成就不能触发吧！

**Comment by Susanping** [comment]
哦哦，额，我可以问你要个QQ号么？哈哈，不给也没关系

**Comment by javaSwing** [comment]
@Susanping java_swing@qq.com
