### ISSUE TITLE
Potential open source license violation

### ISSUE THREAD

**Issue by JokerQyou** [javaSwing/NeteaseCloudWebApp#16]
刚刚发现这个 repo https://github.com/TEsTsLA/NeteaseCloudWebApp ，项目描述中说是“毕业设计，高仿网易云APP的网页”。

![image](https://user-images.githubusercontent.com/1465267/27288779-6770afe6-553a-11e7-8fb3-dafd7a281b19.png)

项目一共只有 3 个 commit，看了一下[中间那个](https://github.com/TEsTsLA/NeteaseCloudWebApp/commit/736b152da05b407b45c99f4a4ad2f4550fb3c28b)批量把各种 URL 替换了，也就是说代码是来自于本项目的。

另外翻了一下你这个项目的 README 和目录结构，似乎并没有指明使用哪种开源协议？那么可以请问他将这个项目修改作为毕业设计的做法经过你的授权了吗？没有经过授权的话，是否可以向 Github 投诉之类的。

**Comment by javaSwing** [comment]
@JokerQyou 我先去看看！
