### ISSUE TITLE
npm run build后,打开dist文件夹里面的index,出现轮播图无数据

### ISSUE THREAD

**Issue by lxk0301** [javaSwing/NeteaseCloudWebApp#17]
已经在index.html里面的script的src加了  <script type=text/javascript src=./static/js/manifest.832b94c3399b5dcebd98.js></script>

**Comment by javaSwing** [comment]
@lxk0301 你是放在服务器上运行的吗？

**Comment by lxk0301** [comment]
不是的,

**Comment by javaSwing** [comment]
@lxk0301 要在服务器上运行才可以，本地打开不行的
