### ISSUE TITLE
楼主你好

### ISSUE THREAD

**Issue by szy1000** [javaSwing/NeteaseCloudWebApp#18]
我想请教一下 我用vue-cli打包的文件 在本地打不开！ 请问 你是怎么做的啊 感谢！在线等

**Comment by javaSwing** [comment]
@szy1000 要放到服务器上！打包完之后，是有说明的！
> Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

**Comment by lxk0301** [comment]
不应该是运行命令让他自己打开的吗?  比如 cnpm run dev

**Comment by szy1000** [comment]
我看楼主的 可以直接打开预览啊

我也看到那个提示命令了

**Comment by javaSwing** [comment]
@szy1000 还是打不开？是不是因为浏览器啊！
