### ISSUE TITLE
测试的时候发现轮播不起作用？

### ISSUE THREAD

**Issue by tuihou123321** [javaSwing/NeteaseCloudWebApp#21]
![image](https://user-images.githubusercontent.com/7146036/31849690-112aef8e-b679-11e7-8c6c-21400563748a.png)

**Comment by javaSwing** [comment]
@tuihou123321 你的MouseUI是用的最新版本吗？

**Comment by fuerpeng** [comment]
我也出现了这个问题 。

**Comment by tuihou123321** [comment]
是最新的，引用方式出现点问题，已经处理好了
