### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by setsuna** [javaSwing/NeteaseCloudWebApp#3]
ERROR in ./src/views/playerDetail.vue

  ✘  http://eslint.org/docs/rules/spaced-comment  Expected space or tab after '//' in comment
  D:\webUI\VUE\gitRep\NeteaseCloudWebApp\src\views\playerDetail.vue:125:10
           //this.afterLrc = [{'txt': '加载歌词失败'}]
            ^

**Comment by javaSwing** [comment]
请在  //后加空格再写注释
