### ISSUE TITLE
eslint错误已经处理  但是又报一个错误

### ISSUE THREAD

**Issue by bookerss** [javaSwing/NeteaseCloudWebApp#4]
✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/indent

> Listening at http://localhost:8080

**Comment by Ale-cc** [comment]
@bookerss 就是空格和冒号的处理  处理完就可以运行了的（报错可以贴详细点）

**Comment by javaSwing** [comment]
@bookerss 对的，你应该贴详细点！

**Comment by javaSwing** [comment]
已经处理，请更新！ @bookerss
