### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhaopei12138** [javaSwing/NeteaseCloudWebApp#6]
http://eslint.org/docs/rules/indent  Expected indentation of 8 spaces but f
ound 9
  D:\wordspace\NeteaseCloudWebApp\src\views\playerDetail.vue:125:10
           this.afterLrc = [{'txt': '加载歌词失败'}]

**Comment by javaSwing** [comment]
你不会使用eslint吗？这上面说的很清楚了

**Comment by LoenDou** [comment]
@javaSwing 最好修改一下Git上的源码吧  down下来的源码都存在playerDetail第125行多一个空格的eslint报错问题

**Comment by javaSwing** [comment]
@LoenDou OK目前在修改中

**Comment by javaSwing** [comment]
已更新，请更新下！
