### ISSUE TITLE
Vue.util.isObject is not a function 已去除eslint 运行报错。

### ISSUE THREAD

**Issue by xiaobebe** [javaSwing/NeteaseCloudWebApp#8]
vue.common.js?b698:422 TypeError: Vue.util.isObject is not a function(…)logError 

@ vue.common.js?b698:422

找不到错误在那里，就是在渲染的时候出错。

**Comment by w515303600** [comment]
vue.common.js?b698:422  TypeError: Vue.util.isObject is not a functio

**Comment by sailingcai** [comment]
我也遇到了同样的问题。

![2017-02-27_01-35-39](https://cloud.githubusercontent.com/assets/102015/23342001/2cb703c4-fc8d-11e6-93b5-7229af4ea92f.png)

**Comment by javaSwing** [comment]
@xiaobebe @sailingcai  是项目一个插件导致了，稍后会上更新！

**Comment by sailingcai** [comment]
给个小建议：在稳定的版本上打个Tag。我等VueJS的初学者一上来就看到一个莫名的错误，很受打击啊。

**Comment by javaSwing** [comment]
谢谢你的建议！ @sailingcai
