### ISSUE TITLE
建议优化：playlistDetail页面中间滚动位置

### ISSUE THREAD

**Issue by sunlianlong** [javaSwing/NeteaseCloudWebApp#9]
playlistDetail中间滚动的body位置可以设置padding-top和padding-bottom将上面的歌单标题和下面的固定位置让出来，这样页面的效果会好一些，目前在此页滚动的时候上面的歌单标题有时会被挡住。另外发先进入页面是否是必须先进入首页然后才能进入歌单页，发现如果单独进入歌单页会没有歌单信息

**Comment by javaSwing** [comment]
谢谢的，你的建议！星期天会进行优化！
